# action for deploying pull request previews

name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: macos-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Packages
        run: npm install
      - name: Build App
        run: npm run build:website
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Copy Static Files
        run: cp -r static/ build/website-next/

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/ # The folder the action should deploy
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
